POST http://localhost:8000/signup/email
Content-Type: application/json

{
  "userEmail": "cs.smoothing@gmail.com"
}

###
GET http://localhost:8000/test/attendance
X-USER-ID: user
Accept: application/json