name: CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
# CI        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

# SonarQube
    - name : Run SonarQube
      if: ${{ success() }}
      run : ${{ secrets.SONAR_COMMAND }}

# CD to server 1
    - name: upload file
      if: ${{ success() }}
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_IP_1 }}
        username: ${{ secrets.SSH_ID }}
        key: ${{ secrets.SSH_KEY_1 }}
        port: ${{ secrets.SSH_PORT }}
        source: "target/*.jar"
        target: "~/"
        rm: false

    - name: execute shell script
      if: ${{ success() }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP_1 }}
        username: ${{ secrets.SSH_ID }}
        key: ${{ secrets.SSH_KEY_1 }}
        port: ${{ secrets.SSH_PORT }}
        script_stop: true
        script: "./start.sh"

# Wait for 30 sec
    - name: Wait for 1 minute
      if: ${{ success() }}
      run: sleep 30

# CD to server2
    - name: upload file
      if: ${{ success() }}
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_IP_2 }}
        username: ${{ secrets.SSH_ID }}
        key: ${{ secrets.SSH_KEY_2 }}
        port: ${{ secrets.SSH_PORT }}
        source: "target/*.jar"
        target: "~/"
        rm: false

    - name: execute shell script
      if: ${{ success() }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP_2 }}
        username: ${{ secrets.SSH_ID }}
        key: ${{ secrets.SSH_KEY_2 }}
        port: ${{ secrets.SSH_PORT }}
        script_stop: true
        script: "./start.sh"
